// LOAD_BEGIN, LOAD_SUCCESS, LOAD_ERROR, RESET


export const REVIEWS = {
    LOAD_BEGIN: "REQUEST_REVIEWS_DATA",
    LOAD_SUCCESS: 'RECEIVE_REVIEWS_DATA',
    LOAD_ERROR: 'ERROR_REVIEWS_DATA',
    RESET: 'RESET_REVIEWS_DATA'
};