// LOAD_BEGIN, LOAD_SUCCESS, LOAD_ERROR, RESET


export const REVIEWS = {
    LOAD_BEGIN: "REQUEST_REVIEWS_DATA",
    LOAD_SUCCESS: 'RECEIVE_REVIEWS_DATA',
    LOAD_ERROR: 'ERROR_REVIEWS_DATA',
    RESET: 'RESET_REVIEWS_DATA'
};

export const PRODUCTS = {
    LOAD_BEGIN: "REQUEST_PRODUCTS_DATA",
    LOAD_SUCCESS: 'RECEIVE_PRODUCTS_DATA',
    LOAD_ERROR: 'ERROR_PRODUCTS_DATA',
    RESET: 'RESET_PRODUCTS_DATA'
};